// This file was generated by json2swift.

import Foundation
import UIKit

/// Represents some information about a Pokémon, but not all. 
public struct PokémonInfo: Codable {
	/// The name of the Pokémon's form
	public let form: String
	
	/// The ID for this form of the Pokémon
	public let id: Int
	
	/// The name of the kind of Pokémon
	public let name: String
	
	/// The national dex number of the Pokémon
	public let ndex: Int
	
	public var formName: String {
		return form.replacingOccurrences(of: name, with: "").replacingOccurrences(of: "(", with: "").replacingOccurrences(of: ")", with: "").replacingOccurrences(of: "Forme", with: "").replacingOccurrences(of: "Form", with: "") .trimmingCharacters(in: .whitespaces).replacingOccurrences(of: "  ", with: " ")
	}
	
	public var icon: UIImage? {
		let formName = "\(self.formName.lowercased().replacingOccurrences(of: "forme", with: "").replacingOccurrences(of: "form", with: "").trimmingCharacters(in: .whitespacesAndNewlines).replacingOccurrences(of: " ", with: "-").replacingOccurrences(of: ":", with: "-").replacingOccurrences(of: "--", with: "-"))".replacingOccurrences(of: "é", with: "e")
		let ndexString = String(ndex)
		let iconName = (formName == "" ? ndexString : [ndexString, formName].joined(separator: "-")) + ".png"
		return UIImage(named: iconName)
	}
}
