// This file was generated by json2swift.

import Foundation
import UIKit

/// Represents some information about a Pokémon, but not all. 
public struct PokémonInfo: Codable {
	/// The name of the Pokémon's form
	public let form: String
	
	/// The ID for this form of the Pokémon
	public let id: Int
	
	/// The name of the kind of Pokémon
	public let name: String
	
	/// The national dex number of the Pokémon
	public let ndex: Int
	
	public init(form: String, id: Int, name: String, ndex: Int) {
		self.form = form
		self.id = id
		self.name = name
		self.ndex = ndex
	}
	public init?(json: [String: Any]) {
		guard let form = json["form"] as? String else { return nil }
		guard let id = json["id"] as? Int else { return nil }
		guard let name = json["name"] as? String else { return nil }
		guard let ndex = json["ndex"] as? Int else { return nil }
		self.init(form: form, id: id, name: name, ndex: ndex)
	}
	
	public var formName: String {
		return form.replacingOccurrences(of: name, with: "").replacingOccurrences(of: "(", with: "").replacingOccurrences(of: ")", with: "").replacingOccurrences(of: "Forme", with: "").replacingOccurrences(of: "Form", with: "") .trimmingCharacters(in: .whitespaces).replacingOccurrences(of: "  ", with: " ")
	}
	
	public var icon: UIImage? {
		let formName = "\(self.formName.lowercased().replacingOccurrences(of: "forme", with: "").replacingOccurrences(of: "form", with: "").trimmingCharacters(in: .whitespacesAndNewlines).replacingOccurrences(of: " ", with: "-").replacingOccurrences(of: ":", with: "-").replacingOccurrences(of: "--", with: "-"))".replacingOccurrences(of: "é", with: "e")
		let ndexString = String(ndex)
		let iconName = (formName == "" ? ndexString : [ndexString, formName].joined(separator: "-")) + ".png"
		return UIImage(named: iconName)
	}
}
